version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
      - ~/.gitconfig:/home/node/.gitconfig:ro
    working_dir: /workspace
    command: sleep infinity
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
      - "8080:8080"
    stdin_open: true
    tty: true
